export  const quotes = ["Megölték a feleségem",
"Belebaszták a Dunába",
"Nyolc éve volt",
"Kellett mennem",
"Azonosítani",
"Mentem a Lenhossekbe",
"Mondtam neki nekem mindig hazudtál",
"A kurva anyósomnak vagy hát volt anyósom",
"Kilenc napig hűtötték",
"Hívogattam mert nem volt meg",
"Aztán harminchárom napra is kellett megint",
"Elvittem a zsidó temetőbe",
"Igen az kibaszott drága volt amúgy",
"Mondta a pasi hogy nyugodtan ájuljak el ő majd megfog",
"De kurva rendes volt amúgy",
"Tényleg",
"Gábor vagyok",
"A nevemre úgyse fogsz emlékezni"]